on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Host Builds

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            rust: stable

    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          sudo apt-get -y install libudev-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./host/phm-cli/Cargo.toml --target=${{ matrix.target }}
